name: RoleplayReactions
main: me.Dary.RoleplayReactions.RoleplayReactions
version: ${project.version}
api-version: 1.19
softdepend: [PlaceholderAPI, DiscordSRV, Essentials]
commands:
   RoleplayReactions:
      description: Commando principal
      usage: /<command>
      aliases: [rr]